### ISSUE TITLE
Error while building in Visual Studio 2019

### ISSUE THREAD

**Issue by physics-sec** [Microwave89/createuserprocess#1]
Hi! You have a really great repo here 😄 
I'm having issues compiling it with Visual Studio 2019
I get this error:
```
1>------ Build started: Project: createuserprocess, Configuration: Release x64 ------
1>Assembling auxfuncs.asm...
1>main.c
1>C:\Users\user\Desktop\createuserprocess\createuserprocess\global.h(17,10): fatal error C1083: Cannot open include file: '..\ndk\ntndk.h': No such file or directory
1>Done building project "createuserprocess.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

`global.h` references `..\ndk\ntndk.h` which isn't present. Any ideas how can I fix this? May be a folder wasn't added to the repo?
Thanks in advance!

**Comment by DownWithUp** [comment]
I'm unsure if @Microwave89 is active very often. However, I was able to fix some of the errors by using ```#include <winternl.h>``` instead of whatever the "ndk\ntndk.h" was. You might also need to link to ntdll.lib. In addition, I commented out the ```#define WIN32_NO_STATUS``` so proper NTSTATUS codes were available. However, the ```RTL_USER_PROCESS_PARAMETERS``` struct is mismatched so you'll need to find/create a new one. Hopefully this helps.

**Comment by physics-sec** [comment]
I will give it a try, thank you!

**Comment by physics-sec** [comment]
In case some is interested, I ended up using the code from [this](https://bitbucket.org/titanengineupdate/titanengine-update/src/0f5566b1dbf98a40d67b491e056ab1c98535d03f/TitanEngine/TitanEngine.Debugger.cpp#lines-323) repo.
Thanks again @DownWithUp!
